version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  greeter_server:
      build:      
        context: ./read_book      
        dockerfile: Dockerfile    
      ports:       
        - "50051:50051"  
  greeter_client: 
      build:      
        context: ./analyse_book      
        dockerfile: Dockerfile
      depends_on:      
          - "greeter_server"    
      command: ["./wait-for-it.sh", "greeter_server:50051", "--", "python", "greeter_client.py"]
  webclient: 
    build:
      context: ./web_display
      dockerfile: Dockerfile
    ports: 
      - "8080:5000"
    depends_on:
      - "redis"
      - "greeter_client"
    environment:
      FLASK_ENV: development
     

